<a href="https://colab.research.google.com/github/danielsmith-cloud/DSRP_inequality/blob/main/DSRP_pip.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Research Question: What country has the hightest poverty rate and how

In [21]:
!pip install matplotlib
import matplotlib.pyplot as plt

!pip install pandas
import pandas as pd

!pip install numpy
import numpy as np

!pip install seaborn
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [22]:
url = "https://raw.githubusercontent.com/owid/poverty-data/refs/heads/main/datasets/pip_dataset.csv"
pip_df = pd.read_csv(url)
pip_df.head()

,country,year,reporting_level,welfare_type,ppp_version,survey_year,survey_comparability,headcount_ratio_international_povline,headcount_ratio_lower_mid_income_povline,headcount_ratio_upper_mid_income_povline,...,decile8_thr,decile9_thr,gini,mld,polarization,palma_ratio,s80_s20_ratio,p90_p10_ratio,p90_p50_ratio,p50_p10_ratio
0,Albania,1996,national,consumption,2011,1996.0,0.0,0.920669,11.174149,44.618417,...,8.85,10.92,0.270103,0.119104,0.241293,0.928335,3.945872,3.568627,1.889273,1.888889
1,Albania,2002,national,consumption,2011,2002.0,1.0,1.570843,14.132118,49.669635,...,8.83,11.58,0.317390,0.164812,0.268982,1.215056,4.831625,3.979381,2.090253,1.903780
2,Albania,2005,national,consumption,2011,2005.0,1.0,0.860527,8.715685,38.545254,...,10.02,12.78,0.305957,0.154413,0.254529,1.142718,4.662236,3.872727,1.978328,1.957576
3,Albania,2008,national,consumption,2011,2008.0,1.0,0.313650,5.250542,31.110345,...,10.74,13.62,0.299847,0.148893,0.247311,1.114657,4.395911,3.574803,1.956897,1.826772
4,Albania,2012,national,consumption,2011,2012.0,1.0,0.849754,6.182414,34.528906,...,10.52,13.26,0.289605,0.138417,0.249988,1.041193,4.272573,3.632877,1.941435,1.871233

In [23]:
print(df.columns.tolist())
print("")
pip_df.info()

['country', 'year', 'reporting_level', 'welfare_type', 'ppp_version', 'survey_year', 'survey_comparability', 'headcount_ratio_international_povline', 'headcount_ratio_lower_mid_income_povline', 'headcount_ratio_upper_mid_income_povline', 'headcount_ratio_100', 'headcount_ratio_1000', 'headcount_ratio_2000', 'headcount_ratio_3000', 'headcount_ratio_4000', 'headcount_ratio_40_median', 'headcount_ratio_50_median', 'headcount_ratio_60_median', 'headcount_international_povline', 'headcount_lower_mid_income_povline', 'headcount_upper_mid_income_povline', 'headcount_100', 'headcount_1000', 'headcount_2000', 'headcount_3000', 'headcount_4000', 'headcount_40_median', 'headcount_50_median', 'headcount_60_median', 'avg_shortfall_international_povline', 'avg_shortfall_lower_mid_income_povline', 'avg_shortfall_upper_mid_income_povline', 'avg_shortfall_100', 'avg_shortfall_1000', 'avg_shortfall_2000', 'avg_shortfall_3000', 'avg_shortfall_4000', 'avg_shortfall_40_median', 'avg_shortfall_50_median', 'avg_shortfall_60_median', 'total_shortfall_international_povline', 'total_shortfall_lower_mid_income_povline', 'total_shortfall_upper_mid_income_povline', 'total_shortfall_100', 'total_shortfall_1000', 'total_shortfall_2000', 'total_shortfall_3000', 'total_shortfall_4000', 'total_shortfall_40_median', 'total_shortfall_50_median', 'total_shortfall_60_median', 'income_gap_ratio_international_povline', 'income_gap_ratio_lower_mid_income_povline', 'income_gap_ratio_upper_mid_income_povline', 'income_gap_ratio_100', 'income_gap_ratio_1000', 'income_gap_ratio_2000', 'income_gap_ratio_3000', 'income_gap_ratio_4000', 'income_gap_ratio_40_median', 'income_gap_ratio_50_median', 'income_gap_ratio_60_median', 'poverty_gap_index_international_povline', 'poverty_gap_index_lower_mid_income_povline', 'poverty_gap_index_upper_mid_income_povline', 'poverty_gap_index_100', 'poverty_gap_index_1000', 'poverty_gap_index_2000', 'poverty_gap_index_3000', 'poverty_gap_index_4000', 'mean', 'median', 'decile1_avg', 'decile2_avg', 'decile3_avg', 'decile4_avg', 'decile5_avg', 'decile6_avg', 'decile7_avg', 'decile8_avg', 'decile9_avg', 'decile10_avg', 'decile1_share', 'decile2_share', 'decile3_share', 'decile4_share', 'decile5_share', 'decile6_share', 'decile7_share', 'decile8_share', 'decile9_share', 'decile10_share', 'decile1_thr', 'decile2_thr', 'decile3_thr', 'decile4_thr', 'decile6_thr', 'decile7_thr', 'decile8_thr', 'decile9_thr', 'gini', 'mld', 'polarization', 'palma_ratio', 's80_s20_ratio', 'p90_p10_ratio', 'p90_p50_ratio', 'p50_p10_ratio']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4877 entries, 0 to 4876
Columns: 108 entries, country to p50_p10_ratio
dtypes: float64(103), int64(2), object(3)
memory usage: 4.0+ MB

In [28]:
pip_df.columns = pip_df.columns.str.replace('_', ' ').str.title()
pip_df.head(20)

,Country,Year,Reporting Level,Welfare Type,Ppp Version,Survey Year,Survey Comparability,Headcount Ratio International Povline,Headcount Ratio Lower Mid Income Povline,Headcount Ratio Upper Mid Income Povline,...,Decile8 Thr,Decile9 Thr,Gini,Mld,Polarization,Palma Ratio,S80 S20 Ratio,P90 P10 Ratio,P90 P50 Ratio,P50 P10 Ratio
0,Albania,1996,national,consumption,2011,1996.00,0.0,0.920669,11.174149,44.618417,...,8.85,10.92,0.270103,0.119104,0.241293,0.928335,3.945872,3.568627,1.889273,1.888889
1,Albania,2002,national,consumption,2011,2002.00,1.0,1.570843,14.132118,49.669635,...,8.83,11.58,0.317390,0.164812,0.268982,1.215056,4.831625,3.979381,2.090253,1.903780
2,Albania,2005,national,consumption,2011,2005.00,1.0,0.860527,8.715685,38.545254,...,10.02,12.78,0.305957,0.154413,0.254529,1.142718,4.662236,3.872727,1.978328,1.957576
3,Albania,2008,national,consumption,2011,2008.00,1.0,0.313650,5.250542,31.110345,...,10.74,13.62,0.299847,0.148893,0.247311,1.114657,4.395911,3.574803,1.956897,1.826772
4,Albania,2012,national,consumption,2011,2012.00,1.0,0.849754,6.182414,34.528906,...,10.52,13.26,0.289605,0.138417,0.249988,1.041193,4.272573,3.632877,1.941435,1.871233
5,Albania,2014,national,consumption,2011,2014.00,2.0,1.580897,11.615621,37.033842,...,11.74,15.78,0.345989,0.198662,0.324310,1.376215,5.930924,5.173770,2.296943,2.252459
6,Albania,2015,national,consumption,2011,2015.00,2.0,0.245098,4.690767,24.461185,...,13.80,18.26,0.327537,0.175495,0.300364,1.248506,5.278241,4.599496,2.229548,2.062972
7,Albania,2016,national,consumption,2011,2016.00,2.0,0.410364,5.462612,23.903491,...,14.78,19.18,0.337363,0.187581,0.314380,1.306972,5.626880,4.930591,2.251174,2.190231
8,Albania,2016,national,income,2011,2016.00,4.0,6.681604,17.621649,39.949891,...,11.88,16.02,0.385656,0.273740,0.350360,1.696002,8.286575,6.965217,2.376855,2.930435
9,Albania,2017,national,consumption,2011,2017.00,2.0,0.428475,4.284743,23.828625,...,14.54,18.82,0.330557,0.179908,0.308522,1.259837,5.389502,4.635468,2.229858,2.078818
10,Albania,2017,national,income,2011,2017.00,4.0,6.073821,15.224104,35.782581,...,12.28,16.44,0.370951,0.254175,0.332537,1.567077,7.732992,6.629032,2.280166,2.907258
11,Albania,2018,national,consumption,2011,2018.00,3.0,0.120772,3.324539,16.861707,...,15.28,19.30,0.301483,0.152404,0.265930,1.083829,4.811264,4.260486,2.002075,2.128035
12,Albania,2018,national,income,2011,2018.00,4.0,4.566243,12.557226,32.385657,...,12.78,17.02,0.359888,0.233051,0.319245,1.482572,7.036721,5.992958,2.233596,2.683099
13,Albania,2019,national,consumption,2011,2019.00,3.0,0.000000,1.198594,9.962062,...,17.60,22.82,0.307717,0.154626,0.274892,1.132010,4.744671,4.141561,2.105166,1.967332
14,Algeria,1988,national,consumption,2011,1988.00,0.0,6.250913,24.466636,57.045164,...,8.27,11.22,0.401949,0.281732,0.307921,1.899252,7.210696,5.123288,2.271255,2.255708
15,Algeria,1995,national,consumption,2011,1995.00,1.0,5.624111,23.540449,54.591619,...,8.66,11.68,0.353301,0.208518,0.313371,1.452068,6.118002,5.168142,2.281250,2.265487
16,Algeria,2011,national,consumption,2011,2011.17,2.0,0.449365,3.744604,28.593149,...,10.60,13.40,0.276157,0.125331,0.226046,0.992916,3.976114,3.350000,1.871508,1.790000
17,Angola,2000,national,consumption,2011,2000.21,0.0,36.374478,59.678611,80.548714,...,5.36,8.06,0.519569,0.512576,0.464340,3.653264,17.654010,12.212121,3.100000,3.939394
18,Angola,2008,national,consumption,2011,2008.50,1.0,34.446857,60.604568,82.921126,...,5.07,6.98,0.427155,0.311632,0.391365,2.147126,8.942374,6.843137,2.674330,2.558824
19,Angola,2018,national,consumption,2011,2018.17,2.0,49.902954,71.484826,88.481178,...,4.07,5.97,0.512721,0.477890,0.470982,3.465666,14.786824,9.950000,3.142105,3.166667